### ISSUE TITLE
[Bug]: (GraphQL) key within "_editableName" property doesn't match order defined in headless template (within block editable)

### ISSUE THREAD

**Issue by basecom-de** [pimcore/data-hub#493]
### Expected behavior

Using the following headless template:

```
layout: simple
group: null
content:
    testBlock:
        type: block
        label: testBlock
        config:
            limit: 10
            reload: false
            default: 0
        items:
            testInput:
                type: input
                label: testInput
```
create the following headless template content:

<img width="848" alt="Bildschirmfoto 2022-03-11 um 09 24 58" src="https://user-images.githubusercontent.com/29371208/157830156-216f4a76-bb15-45b2-8aea-ea6088977062.png">

reading the document editables via a DataHub connection (of the Type GraphQL) will result in the following output:

<img width="1561" alt="Bildschirmfoto 2022-03-11 um 09 07 22" src="https://user-images.githubusercontent.com/29371208/157830283-624fe510-6f6c-48e6-8830-e2e8b0d63038.png">

**Expected behaviour would be that the key within the "_editableName"  property would match their defined order**

### Actual behavior

See above

### Steps to reproduce

See above
