### ISSUE TITLE
[Bug]: GraphQl results doesn't get Cached with Redis

### ISSUE THREAD

**Issue by ayoob-lfc** [pimcore/data-hub#775]
### Expected behavior

When you use Redis for caching the results should get cached.

i.e if you add logs here to capture the value you should get your response:

https://github.com/pimcore/data-hub/blob/74b345701d83a6377004cd9c88b2655ce1a94cdf/src/Service/OutputCacheService.php#L106

### Actual behavior

The log results comeback empty.

### Steps to reproduce

1 - Install Pimcore 11 skeleton
2 - Install Data-hub
3 - Create a GraphQl query
4 - Set Redis tag aware for cache

```
framework:
    cache:
        pools:
            pimcore.cache.pool:
                public: true
                default_lifetime: 31536000  # 1 year
                tags: true
                adapter: pimcore.cache.adapter.redis_tag_aware
                provider: 'redis://redis'
```

5 - Add logs here to log the output:

https://github.com/pimcore/data-hub/blob/74b345701d83a6377004cd9c88b2655ce1a94cdf/src/Service/OutputCacheService.php#L106
