### ISSUE TITLE
[Bug]: Pimcore 10: Symfony config has no effect on the storage type

### ISSUE THREAD

**Issue by dvesh3** [pimcore/data-hub#779]
### Expected behavior

Symfony config is used for reading and writing data hub config files

### Actual behavior

Symfony config has no effect

### Steps to reproduce

Pimcore 10.6

1. Add config:
```yaml
pimcore_data_hub:
    config_location: 
        data_hub:
            write_target:
                type: 'symfony-config'
                options:
                     directory: '/var/www/html/var/config/data-hub-custom'
```

2. Add new datahub graphql configuration
3. Config is still stored on default storage in db table `settings-store`

Reason: the config is used only on v11 https://github.com/pimcore/data-hub/blob/323590cf0952d0f958e8b3f15757f7a7cd679f64/src/DependencyInjection/PimcoreDataHubExtension.php#L57-L60
