### ISSUE TITLE
[Bug]: labels get lowercased

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/data-hub#846]
### Expected behavior

The labeled field is exported exactly like the label.

### Actual behavior

The labeled field is lowercased.

### Steps to reproduce

1. Create a field like so

```yaml
                                -
                                    isOperator: true
                                    attributes:
                                        label: Image
                                        type: operator
                                        class: assets
                                        children:
                                            -
                                                isOperator: false
                                                attributes:
                                                    label: 'Category Image'
                                                    type: value
                                                    class: DefaultValue
                                                    attribute: image
                                                    dataType: image
                                                    children: {  }
```

2. create a query like so

```graphql
getProductCategoryListing {edges {node {id, Image{id, fullpath, url}}}}
```

3. get error
```
GraphQL query failed: Cannot query field "Image" on type "object_ProductCategory". Did you mean "image" or "tags"?
```
4. try with lowercase label

```graphql
getProductCategoryListing {edges {node {id, image{id, fullpath, url}}}}
```

5. it works like that
