### ISSUE TITLE
[Bug]: UI remains readonly in dev-env and configurations in yml have no effect

### ISSUE THREAD

**Issue by MLindenhofer** [pimcore/data-hub#981]
### Expected behavior

In dev-env the Save Button should be not read-only and changes in yaml should not be ignored. 

### Actual behavior

I can't apply changes on my configurations anymore. The UI Save button remains in read-only state even in dev environment. So I tried to do the changes I needed to do via the yaml-file, but even after running the cache-clear & rebuild workspace and rebuild definitions command my changes did not appear in the admin backend. Every change in my ShopData.yaml in /var/config/data_hub/ is ignored.

### Steps to reproduce

pimcore 11.1.6 
datahub version 1.7.4  

I also have this setting in my root config/packages/dev/pimcore_data_hub.yaml:

```
pimcore_data_hub:
    config_location:
        data_hub:
            write_target:
                type: 'symfony-config'
                options:
                    directory: '/Volumes/projects/myproject/var/config/data_hub/'
```

ShopData.yaml (sample)

```
pimcore_data_hub:
    configurations:
        ShopData:
            general:
                active: true
                type: graphql
                name: ShopData
                description: ''
                group: ''
                sqlObjectCondition: ''
                modificationDate: 1749044226
                path: null
                createDate: 1690875689
            schema:
                queryEntities:
                    Brands:
                        id: Brands
                        name: Brands
                        columnConfig:
                            columns:
                                -   attributes:
                                        attribute: BrandID
                                        label: BrandID
                                        dataType: input
                                    isOperator: false
                                -   attributes:
                                        attribute: Name
                                        label: Name
                                        dataType: input
                                    isOperator: false
                                -   attributes:
                                        attribute: Marketingbezeichnung
                                        label: Marketingbezeichnung
                                        dataType: input
                                    isOperator: false
                                -   attributes:
                                        attribute: AlternativeSuchbezeichnung
                                        label: 'alternative Bezeichnungen für Suche'
                                        dataType: input
                                    isOperator: false
                                -   attributes:
                                        attribute: inMarketingssliderZeigen
                                        label: 'im Markenslider auf Startseite anzeigen'
                                        dataType: checkbox
                                    isOperator: false
                                -   attributes:
                                        attribute: Products
                                        label: Products
                                        dataType: reverseObjectRelation
                                    isOperator: false
                                -   attributes:
                                        attribute: Logo
                                        label: Logo
                                        dataType: image
                                    isOperator: false
                                -   attributes:
                                        attribute: id
                                        label: ID
                                        dataType: system
                                    isOperator: false
                                -   attributes:
                                        attribute: fullpath
                                        label: 'Full Path'
                                        dataType: system
                                    isOperator: false
                                -   attributes:
                                        attribute: published
                                        label: Published
                                        dataType: system
                                    isOperator: false
                                -   attributes:
                                        attribute: key
                                        label: Key
                                        dataType: system
                                    isOperator: false
                                -   attributes:
                                        attribute: modificationDate
                                        label: modificationDate
                                        dataType: system
                                    isOperator: false
```

The only thing I noticed too is that the same behavior is in the "System Settings". 

Has somebody of you experienced similar problems?

Thanks in advance
